# Generated by Django 3.1.4 on 2020-12-21 10:25

from django.db import migrations
from django.conf import settings

import os
import csv

DATE = 0
NUMBER = 1
NAME = 2
TYPE1 = 3
TYPE2 = 4
HP = 5
ATTACK = 6
DEFENSE = 7
SP_ATK = 8
SP_DEF = 9
SPEED = 10
GENERATION = 11
LEGENDARY = 12


def load_pokemon_data(apps, schema_editor):
    Pokemon = apps.get_model('api', 'Pokemon')

    with open(settings.DATA_DIR / 'pokemon.csv', newline='') as csvfile:
        pokemon_reader = csv.reader(csvfile, delimiter=',')
        next(pokemon_reader)  # skip first row
        for row in pokemon_reader:
            Pokemon.objects.create(
                number=row[NUMBER],
                name=row[NAME],
                type1=row[TYPE1],
                type2=row[TYPE2],
                hp=row[HP],
                attack=row[ATTACK],
                defense=row[DEFENSE],
                sp_atk=row[SP_ATK],
                sp_def=row[SP_DEF],
                speed=row[SPEED],
                generation=row[GENERATION],
                legendary=True if row[LEGENDARY] == 'TRUE' else False,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_pokemon_data, reverse_code=migrations.RunPython.noop),
    ]
