# Generated by Django 3.1.4 on 2021-03-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pokemon_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of invoice')),
                ('number', models.PositiveIntegerField(verbose_name='Invoice number')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('zipcode', models.CharField(max_length=100, verbose_name='Zip Code')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('item_name', models.CharField(max_length=100, verbose_name='Item Purchased')),
                ('price_net', models.FloatField(max_length=100, verbose_name='Net Price')),
                ('vat', models.FloatField(max_length=100, verbose_name='VAT')),
                ('price_gross', models.FloatField(max_length=100, verbose_name='Gross Price')),
                ('paid', models.BooleanField(default=False, verbose_name='Is this invoice already paid?')),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='PokeDex index number')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the Pokemon')),
                ('type1', models.CharField(max_length=50, verbose_name='Type of Pokemon')),
                ('type2', models.CharField(max_length=50, verbose_name='Other Type of Pokemon')),
                ('hp', models.IntegerField(verbose_name='Hit Points')),
                ('attack', models.IntegerField(verbose_name='Attack Strength')),
                ('defense', models.IntegerField(verbose_name='Defensive Strength')),
                ('sp_atk', models.IntegerField(verbose_name='Special Attack Strength')),
                ('sp_def', models.IntegerField(verbose_name='Special Defensive Strength')),
                ('speed', models.IntegerField(verbose_name='Speed')),
                ('generation', models.IntegerField(verbose_name='Generation')),
                ('legendary', models.BooleanField(default=False, verbose_name='Legendary Pokemon?')),
            ],
            options={
                'ordering': ('number', 'name'),
            },
        ),
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ('number', 'name')},
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type1',
            field=models.CharField(max_length=50, verbose_name='Type of Pokemon'),
        ),
    ]
