# Generated by Django 3.1.4 on 2021-03-26 11:58

from django.db import migrations
from django.conf import settings

import os
import csv

NUMBER = 0
DATE = 1
NAME = 2
ADDRESS = 3
ZIPCODE = 4
CITY = 5
COUNTRY = 6
ITEM_NAME = 7
PRICE_NET = 8
VAT = 9
PRICE_GROSS = 10
PAID = 11

def load_invoice_data(apps, schema_editor):
    Invoice = apps.get_model('api', 'Invoice')

    with open(settings.DATA_DIR / 'invoices.csv', newline='') as csvfile:
        pokemon_reader = csv.reader(csvfile, delimiter=',')
        next(pokemon_reader)  # skip first row
        for row in pokemon_reader:
            Invoice.objects.create(
                number=row[NUMBER],
                date=row[DATE],
                name=row[NAME],
                address=row[ADDRESS],
                zipcode=row[ZIPCODE],
                city=row[CITY],
                country=row[COUNTRY],
                item_name=row[ITEM_NAME],
                price_net=row[PRICE_NET],
                vat=row[VAT],
                price_gross=row[PRICE_GROSS],
                paid=True if row[PAID] == 'TRUE' else False,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210326_1311'),
    ]

    operations = [
        migrations.RunPython(load_invoice_data, reverse_code=migrations.RunPython.noop),
    ]
